### ISSUE TITLE
HOWTO join grafadruid.slack.com

### ISSUE THREAD

**Issue by vigith** [grafadruid/go-druid#2]
When I click on https://grafadruid.slack.com, it expects me to have an account and I do not have. I would like to know more about the project as we use `golang` heavily and is evaluating `druid` as our OLAP system.

**Comment by jbguerraz** [comment]
Hello @vigith !
Yes, you need an account to use Slack. You can easilly create one in few clicks.
Otherwhise, I just enabled "Discussions" feature here on Github, feel free to use it: https://github.com/grafadruid/go-druid/discussions !
We'll be happy to help :)

**Comment by vigith** [comment]
May be I need an invitation to join the grafadruid.slack.com? Thank you for enabling discussion.

**Comment by jbguerraz** [comment]
Sorry! Here it is: https://join.slack.com/t/grafadruid/shared_invite/zt-kxaiq5gm-c6akAiceMzgHvUBV~KXeiA

Replaced the link on the project description. That stuff will need some automation I bet since the link is active for 30 days / 2K users. Or maybe another place than Slack. Something to dig later :)
